/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.DLInformation;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author sushm
 */
public class CreateDLInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDLInfoJPanel
     */
    DLInformation dLInformation;
    public CreateDLInfoJPanel(DLInformation dLInformation) {
        initComponents();
        this.dLInformation = dLInformation;
    }
//    CreateDLInfoJPanel(DLInformation dLInformation) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateDL = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        lblDateIssued = new javax.swing.JLabel();
        lblDateOfExpiration = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        txtDOI = new javax.swing.JTextField();
        txtDOE = new javax.swing.JTextField();
        btnCreateDL = new javax.swing.JButton();
        lblDLPicture = new javax.swing.JLabel();
        btnUploadPic = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateDL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateDL.setForeground(new java.awt.Color(0, 153, 153));
        lblCreateDL.setText("Driver's License");
        add(lblCreateDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 540, -1));
        add(txtBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 244, -1));

        lblLicenseNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLicenseNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblLicenseNumber.setText("License Number:");
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 71, 110, 20));

        lblDateIssued.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateIssued.setForeground(new java.awt.Color(102, 102, 102));
        lblDateIssued.setText("Date Issued:");
        add(lblDateIssued, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 104, 110, 20));

        lblDateOfExpiration.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateOfExpiration.setForeground(new java.awt.Color(102, 102, 102));
        lblDateOfExpiration.setText("Date Of Expiration");
        add(lblDateOfExpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 135, 130, 20));

        lblBloodType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(102, 102, 102));
        lblBloodType.setText("Blood Type");
        add(lblBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 173, 110, 20));
        add(txtLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 244, -1));
        add(txtDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 244, -1));
        add(txtDOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 244, -1));

        btnCreateDL.setText("Create");
        btnCreateDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDLActionPerformed(evt);
            }
        });
        add(btnCreateDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 250, -1));

        lblDLPicture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDLPicture.setForeground(new java.awt.Color(102, 102, 102));
        lblDLPicture.setText("DL Pic");
        add(lblDLPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnUploadPic.setText("Upload");
        btnUploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPicActionPerformed(evt);
            }
        });
        add(btnUploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDLActionPerformed
        // TODO add your handling code here:
        dLInformation.setLicenseNum(txtLN.getText());
        dLInformation.setDateOfIssue(txtDOI.getText());
        dLInformation.setDateOfExpiry(txtDOE.getText());
        dLInformation.setBloodType(txtBloodType.getText());
        
        JOptionPane.showMessageDialog(this, "DL Information Saved.");
    }//GEN-LAST:event_btnCreateDLActionPerformed

    private void btnUploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPicActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        dLInformation.setPicture(filename);
    }//GEN-LAST:event_btnUploadPicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDL;
    private javax.swing.JButton btnUploadPic;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCreateDL;
    private javax.swing.JLabel lblDLPicture;
    private javax.swing.JLabel lblDateIssued;
    private javax.swing.JLabel lblDateOfExpiration;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDOI;
    private javax.swing.JTextField txtLN;
    // End of variables declaration//GEN-END:variables
}
