/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.BankingInformation;
import javax.swing.JOptionPane;

/**
 *
 * @author sushm
 */
public class CreateCheckingAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankingInfoJPanel
     */
    BankingInformation checkingAccount;
    public CreateCheckingAccount(BankingInformation checkingAccount) {
        initComponents();
        this.checkingAccount = checkingAccount;
    }

//    CreateCheckingAccount(BankingInformation checkingAccount) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCheckingAccount = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtBRNum = new javax.swing.JTextField();
        txtAccNum = new javax.swing.JTextField();
        txtAccTyp = new javax.swing.JTextField();
        txtAccBal = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutingNumber = new javax.swing.JLabel();
        btnCreateCA = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCheckingAccount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCheckingAccount.setForeground(new java.awt.Color(0, 153, 153));
        lblCheckingAccount.setText("Checking Account");
        add(lblCheckingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 360, 20));

        lblBankAccountNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankAccountNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblBankAccountNumber.setText("Bank Account Number:");
        add(lblBankAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 131, 130, 20));

        lblAccountBalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccountBalance.setForeground(new java.awt.Color(102, 102, 102));
        lblAccountBalance.setText("Account Balance:");
        add(lblAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 162, 100, 20));

        lblAccountType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccountType.setForeground(new java.awt.Color(102, 102, 102));
        lblAccountType.setText("Account Type:");
        add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 200, 90, 20));
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 62, 220, -1));
        add(txtBRNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 93, 220, -1));
        add(txtAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 131, 220, -1));
        add(txtAccTyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 200, 220, -1));
        add(txtAccBal, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 162, 220, -1));

        lblBankName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(102, 102, 102));
        lblBankName.setText("Bank Name:");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 62, 80, 20));

        lblBankRoutingNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankRoutingNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblBankRoutingNumber.setText("Bank Routing Number:");
        add(lblBankRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 130, 20));

        btnCreateCA.setText("Create");
        btnCreateCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCAActionPerformed(evt);
            }
        });
        add(btnCreateCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 238, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCAActionPerformed
        // TODO add your handling code here:
        
        checkingAccount.setBankName(txtBankName.getText());
        checkingAccount.setBankRountingNum(txtBRNum.getText());
        checkingAccount.setAccNum(txtAccNum.getText());
        checkingAccount.setAccBalance(txtAccBal.getText());
        checkingAccount.setAccType(txtAccTyp.getText());
        
        JOptionPane.showMessageDialog(this, "Checkings Bank Information Saved.");
    }//GEN-LAST:event_btnCreateCAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCA;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblCheckingAccount;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtAccTyp;
    private javax.swing.JTextField txtBRNum;
    private javax.swing.JTextField txtBankName;
    // End of variables declaration//GEN-END:variables
}
