/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.MedRecord;
import Model.MedRecord;
import javax.swing.JOptionPane;
/**
 *
 * @author sushm
 */
public class CreateMedRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMedRecordJPanel
     */
    MedRecord medRecord;
    public CreateMedRecordJPanel(MedRecord medRecord) {
        initComponents();
        this.medRecord = medRecord;
    }

//    CreateMedRecordJPanel(MedRecord medRecord) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedRecNum = new javax.swing.JLabel();
        lblAllergy1 = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        lblMedicalRecord = new javax.swing.JLabel();
        btnCreateMedRec = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedRecNum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMedRecNum.setForeground(new java.awt.Color(102, 102, 102));
        lblMedRecNum.setText("Med Record Number:");
        add(lblMedRecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblAllergy1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAllergy1.setForeground(new java.awt.Color(102, 102, 102));
        lblAllergy1.setText("Allergy1:");
        add(lblAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        lblAllergy2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAllergy2.setForeground(new java.awt.Color(102, 102, 102));
        lblAllergy2.setText("Allergy2:");
        add(lblAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lblAllergy3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAllergy3.setForeground(new java.awt.Color(102, 102, 102));
        lblAllergy3.setText("Allergy3:");
        add(lblAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        add(txtAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, -1));

        txtAllergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy3ActionPerformed(evt);
            }
        });
        add(txtAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));
        add(txtMedRecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));
        add(txtAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        lblMedicalRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMedicalRecord.setForeground(new java.awt.Color(0, 153, 153));
        lblMedicalRecord.setText("Medical Record");
        add(lblMedicalRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 20));

        btnCreateMedRec.setText("Create");
        btnCreateMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedRecActionPerformed(evt);
            }
        });
        add(btnCreateMedRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAllergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy3ActionPerformed

    private void btnCreateMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedRecActionPerformed
        // TODO add your handling code here:
        
        medRecord.setMedRecordNum(txtMedRecNum.getText());
        medRecord.setAlergy1(txtAllergy1.getText());
        medRecord.setAlergy2(txtAllergy2.getText());
        medRecord.setAlergy3(txtAllergy3.getText());
        
        JOptionPane.showMessageDialog(this, "Medical Record Saved.");
       
        
    }//GEN-LAST:event_btnCreateMedRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateMedRec;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtMedRecNum;
    // End of variables declaration//GEN-END:variables
}
