/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;
import Model.DemoGraphicInformation;
import javax.swing.JOptionPane;

/**
 *
 * @author sushm
 */
public class CreateDemoGraphicInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDemoGraphicInfoJPanel
     */
    DemoGraphicInformation Demograp;
    public CreateDemoGraphicInfoJPanel(DemoGraphicInformation Demograp) {
        initComponents();
        this.Demograp = Demograp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(102, 102, 102));
        lblFirstName.setText("First Name:");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 20));

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(102, 102, 102));
        lblLastName.setText("Last Name:");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 20));

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblPhoneNumber.setText("Phone Number:");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 20));

        lblDob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDob.setForeground(new java.awt.Color(102, 102, 102));
        lblDob.setText("D.O.B:");
        add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, -1));

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAge.setForeground(new java.awt.Color(102, 102, 102));
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, -1));

        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(102, 102, 102));
        lblHeight.setText("Height:");
        add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, -1));

        lblWeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(102, 102, 102));
        lblWeight.setText("Weight:");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 60, -1));

        lblSSN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(102, 102, 102));
        lblSSN.setText("SSN:");
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, -1));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, -1));
        add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, -1));
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, -1));

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Demographic Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Demograp.setFirstName(txtFirstName.getText());
        Demograp.setLastName(txtLastName.getText());
        Demograp.setPhoneNumber(txtPhoneNumber.getText());
        Demograp.setDateOfBirth(txtDob.getText());
        Demograp.setHeight(txtHeight.getText());
        Demograp.setWeight(txtWeight.getText());
        Demograp.setAge(txtAge.getText());
        Demograp.setSSN(txtSSN.getText());
        
        JOptionPane.showMessageDialog(this, "Demographic Information Saved.");
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
