/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.DemoGraphicInformation;
import Model.AddressInformation;
import Model.BankingInformation;
import Model.DLInformation;
import Model.MedRecord;

/**
 *
 * @author sushm
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    DemoGraphicInformation demoGraphicInformation;
    AddressInformation addressInformation;
    BankingInformation savingsAccount;
    BankingInformation checkingAccount;
    DLInformation dLInformation;
    MedRecord medRecord;
    
    public MainJFrame() {
        initComponents();
        
        demoGraphicInformation = new DemoGraphicInformation();
        addressInformation = new AddressInformation();
        savingsAccount  = new BankingInformation();
        checkingAccount = new BankingInformation();
        dLInformation = new DLInformation();
        medRecord = new MedRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreateDemoGraphicInfo = new javax.swing.JButton();
        btnViewDemoGraphicInfo = new javax.swing.JButton();
        btnCreateAddressInfo = new javax.swing.JButton();
        btnViewAddressInfo = new javax.swing.JButton();
        btnCreateDLInfo = new javax.swing.JButton();
        btnViewDLInfo = new javax.swing.JButton();
        btnCreateSavingAccount = new javax.swing.JButton();
        btnViewSavingAccount = new javax.swing.JButton();
        btnCreateMedRecord = new javax.swing.JButton();
        btnViewMedRecord = new javax.swing.JButton();
        btnCreateCheckingAccount = new javax.swing.JButton();
        btnViewCheckingAccount = new javax.swing.JButton();
        btnCompRepo = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(233, 232, 234));

        btnCreateDemoGraphicInfo.setText("Create DemoGraphic Info");
        btnCreateDemoGraphicInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateDemoGraphicInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDemoGraphicInfoActionPerformed(evt);
            }
        });

        btnViewDemoGraphicInfo.setText("View DemoGraphic Info");
        btnViewDemoGraphicInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDemoGraphicInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDemoGraphicInfoActionPerformed(evt);
            }
        });

        btnCreateAddressInfo.setText("Create Address Info");
        btnCreateAddressInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateAddressInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressInfoActionPerformed(evt);
            }
        });

        btnViewAddressInfo.setText("View Address Info");
        btnViewAddressInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewAddressInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddressInfoActionPerformed(evt);
            }
        });

        btnCreateDLInfo.setText("Create DL Info");
        btnCreateDLInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateDLInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDLInfoActionPerformed(evt);
            }
        });

        btnViewDLInfo.setText("View DL Info");
        btnViewDLInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDLInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDLInfoActionPerformed(evt);
            }
        });

        btnCreateSavingAccount.setText("Create Saving Account");
        btnCreateSavingAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavingAccountActionPerformed(evt);
            }
        });

        btnViewSavingAccount.setText("View Saving Account");
        btnViewSavingAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavingAccountActionPerformed(evt);
            }
        });

        btnCreateMedRecord.setText("Create Med Record");
        btnCreateMedRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateMedRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedRecordActionPerformed(evt);
            }
        });

        btnViewMedRecord.setText("View Med Record");
        btnViewMedRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewMedRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedRecordActionPerformed(evt);
            }
        });

        btnCreateCheckingAccount.setText("Create Checking Account");
        btnCreateCheckingAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateCheckingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckingAccountActionPerformed(evt);
            }
        });

        btnViewCheckingAccount.setText("View Checking Account");
        btnViewCheckingAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewCheckingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingAccountActionPerformed(evt);
            }
        });

        btnCompRepo.setText("View Complete Report");
        btnCompRepo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompRepoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewDemoGraphicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDemoGraphicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnCreateAddressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAddressInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateSavingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewSavingAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMedRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMedRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCheckingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCheckingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateDemoGraphicInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAddressInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateSavingAccount)
                .addGap(9, 9, 9)
                .addComponent(btnCreateCheckingAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDLInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateMedRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(btnViewDemoGraphicInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAddressInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewSavingAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCheckingAccount)
                .addGap(5, 5, 5)
                .addComponent(btnViewDLInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMedRecord)
                .addGap(38, 38, 38)
                .addComponent(btnCompRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setMaximumSize(new java.awt.Dimension(500, 650));
        workArea.setMinimumSize(new java.awt.Dimension(500, 650));
        workArea.setPreferredSize(new java.awt.Dimension(500, 650));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDemoGraphicInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDemoGraphicInfoActionPerformed
        // TODO add your handling code here:
        ViewDemoGraphicInfoJPanel viewDemographicJpanel =new ViewDemoGraphicInfoJPanel(demoGraphicInformation);
        splitPane.setRightComponent(viewDemographicJpanel);
    }//GEN-LAST:event_btnViewDemoGraphicInfoActionPerformed

    private void btnCreateDemoGraphicInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDemoGraphicInfoActionPerformed
        // TODO add your handling code here:
        CreateDemoGraphicInfoJPanel createDemoGraphicInfoJPanel = new CreateDemoGraphicInfoJPanel(demoGraphicInformation);
        splitPane.setRightComponent(createDemoGraphicInfoJPanel);
    }//GEN-LAST:event_btnCreateDemoGraphicInfoActionPerformed

    private void btnCreateAddressInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressInfoActionPerformed
        // TODO add your handling code here:
        CreateAddressInfoJPanel createAddressInfoJPanel = new CreateAddressInfoJPanel(addressInformation);
        splitPane.setRightComponent(createAddressInfoJPanel);
    }//GEN-LAST:event_btnCreateAddressInfoActionPerformed

    private void btnViewAddressInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddressInfoActionPerformed
        // TODO add your handling code here:
        ViewAddressInfoJPanel viewAddressInfoJPanel = new ViewAddressInfoJPanel(addressInformation);
        splitPane.setRightComponent(viewAddressInfoJPanel);
    }//GEN-LAST:event_btnViewAddressInfoActionPerformed

    private void btnCreateSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavingAccountActionPerformed
        // TODO add your handling code here:
        CreateSavingAccount createSavingAccount = new CreateSavingAccount(savingsAccount);
        splitPane.setRightComponent(createSavingAccount);
    }//GEN-LAST:event_btnCreateSavingAccountActionPerformed

    private void btnViewSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavingAccountActionPerformed
        // TODO add your handling code here:
        ViewSavingAccountJPanel viewSavingAccountJPanel = new ViewSavingAccountJPanel(savingsAccount);
        splitPane.setRightComponent(viewSavingAccountJPanel);
    }//GEN-LAST:event_btnViewSavingAccountActionPerformed

    private void btnCreateCheckingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckingAccountActionPerformed
        // TODO add your handling code here:
        CreateCheckingAccount createCheckingAccount = new CreateCheckingAccount(checkingAccount);
        splitPane.setRightComponent(createCheckingAccount);
    }//GEN-LAST:event_btnCreateCheckingAccountActionPerformed

    private void btnViewCheckingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingAccountActionPerformed
        // TODO add your handling code here:
        ViewCheckingAccountJPanel checkingAccountJPanel = new ViewCheckingAccountJPanel(checkingAccount);
        splitPane.setRightComponent(checkingAccountJPanel);
    }//GEN-LAST:event_btnViewCheckingAccountActionPerformed

    private void btnCreateDLInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDLInfoActionPerformed
        // TODO add your handling code here:
        CreateDLInfoJPanel createDLInfoJPanel = new CreateDLInfoJPanel(dLInformation);
        splitPane.setRightComponent(createDLInfoJPanel);
    }//GEN-LAST:event_btnCreateDLInfoActionPerformed

    private void btnCreateMedRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedRecordActionPerformed
        // TODO add your handling code here:
        CreateMedRecordJPanel createMedRecordJPanel = new CreateMedRecordJPanel(medRecord);
        splitPane.setRightComponent(createMedRecordJPanel);
    }//GEN-LAST:event_btnCreateMedRecordActionPerformed

    private void btnViewMedRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedRecordActionPerformed
        // TODO add your handling code here:
        ViewMedRecordJPanel viewMedRecordJPanel = new ViewMedRecordJPanel(medRecord);
        splitPane.setRightComponent(viewMedRecordJPanel);
    }//GEN-LAST:event_btnViewMedRecordActionPerformed

    private void btnViewDLInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDLInfoActionPerformed
        // TODO add your handling code here:
        ViewDLInfoJPanel viewDLInfoJPanel = new ViewDLInfoJPanel(dLInformation);
        splitPane.setRightComponent(viewDLInfoJPanel);
    }//GEN-LAST:event_btnViewDLInfoActionPerformed

    private void btnCompRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompRepoActionPerformed
        // TODO add your handling code here:
        ViewCompleteReportJPanel viewCompleteReportJPanel = new ViewCompleteReportJPanel(demoGraphicInformation,addressInformation,savingsAccount,checkingAccount,dLInformation,medRecord);
        splitPane.setRightComponent(viewCompleteReportJPanel);
    }//GEN-LAST:event_btnCompRepoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompRepo;
    private javax.swing.JButton btnCreateAddressInfo;
    private javax.swing.JButton btnCreateCheckingAccount;
    private javax.swing.JButton btnCreateDLInfo;
    private javax.swing.JButton btnCreateDemoGraphicInfo;
    private javax.swing.JButton btnCreateMedRecord;
    private javax.swing.JButton btnCreateSavingAccount;
    private javax.swing.JButton btnViewAddressInfo;
    private javax.swing.JButton btnViewCheckingAccount;
    private javax.swing.JButton btnViewDLInfo;
    private javax.swing.JButton btnViewDemoGraphicInfo;
    private javax.swing.JButton btnViewMedRecord;
    private javax.swing.JButton btnViewSavingAccount;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
