/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.BankingInformation;

/**
 *
 * @author sushm
 */
public class ViewCheckingAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankingInfoJPanel
     */
    BankingInformation bankingInformation;
    public ViewCheckingAccountJPanel(BankingInformation bankingInformation) {
        initComponents();
        this.bankingInformation = bankingInformation;
        diplayCheckBankingInfo();
    }

//    ViewCheckingAccountJPanel(BankingInformation checkingAccount) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAccNum = new javax.swing.JTextField();
        txtAccTyp = new javax.swing.JTextField();
        txtAccBal = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutingNumber = new javax.swing.JLabel();
        lblCheckingAccount = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtBRNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 244, -1));
        add(txtAccTyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 244, -1));
        add(txtAccBal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 244, -1));

        lblBankName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(102, 102, 102));
        lblBankName.setText("Bank Name:");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 90, 20));

        lblBankRoutingNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankRoutingNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblBankRoutingNumber.setText("Bank Routing Number:");
        add(lblBankRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 20));

        lblCheckingAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCheckingAccount.setForeground(new java.awt.Color(0, 153, 153));
        lblCheckingAccount.setText("Checking Account");
        add(lblCheckingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 513, -1));

        lblBankAccountNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBankAccountNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblBankAccountNumber.setText("Bank Account Number:");
        add(lblBankAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 20));

        lblAccountBalance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccountBalance.setForeground(new java.awt.Color(102, 102, 102));
        lblAccountBalance.setText("Account Balance:");
        add(lblAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 20));

        lblAccountType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccountType.setForeground(new java.awt.Color(102, 102, 102));
        lblAccountType.setText("Account Type:");
        add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 20));
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 244, -1));
        add(txtBRNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 244, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblCheckingAccount;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtAccTyp;
    private javax.swing.JTextField txtBRNum;
    private javax.swing.JTextField txtBankName;
    // End of variables declaration//GEN-END:variables

    private void diplayCheckBankingInfo() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        txtBankName.setText(bankingInformation.getBankName());
        txtBRNum.setText(bankingInformation.getBankRountingNum());
        txtAccNum.setText(bankingInformation.getAccNum());
        txtAccBal.setText(bankingInformation.getAccBalance());
        txtAccTyp.setText(bankingInformation.getAccType());
    }
}
