/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;
import Model.AddressInformation;
/**
 *
 * @author sushm
 */
public class ViewAddressInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAddressInfoJPanel
     */
    
    AddressInformation addressInformation;
    
    public ViewAddressInfoJPanel(AddressInformation addressInformation) {
        initComponents();
        this.addressInformation = addressInformation;
        displayAddressInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStreetAdd = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStreetAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStreetAdd.setForeground(new java.awt.Color(102, 102, 102));
        lblStreetAdd.setText("Street Address:");
        add(lblStreetAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCity.setForeground(new java.awt.Color(102, 102, 102));
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, -1));

        lblState.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblState.setForeground(new java.awt.Color(102, 102, 102));
        lblState.setText("State:");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblZipCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(102, 102, 102));
        lblZipCode.setText("ZipCode:");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Address Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayAddressInfo() {
        
        txtCity.setText(addressInformation.getCity());
        txtStreet.setText(addressInformation.getStreetAddress());
        txtState.setText(addressInformation.getState());
        txtZipCode.setText(addressInformation.getZipCode());
    }
}
