/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;
import Model.DLInformation;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/**
 *
 * @author sushm
 */
public class ViewDLInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDLInfoJPanel
     */
    DLInformation dLInformation;
    public ViewDLInfoJPanel(DLInformation dLInformation) {
        initComponents();
        this.dLInformation = dLInformation;
        displayDLInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateDL = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        lblDateIssued = new javax.swing.JLabel();
        lblDateOfExpiration = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        txtDateIssued = new javax.swing.JTextField();
        txtDOE = new javax.swing.JTextField();
        lblUploadPicture = new javax.swing.JLabel();
        lblDisplayPic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateDL.setBackground(new java.awt.Color(255, 255, 255));
        lblCreateDL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateDL.setForeground(new java.awt.Color(0, 153, 153));
        lblCreateDL.setText("Driver's License");
        add(lblCreateDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 20));
        add(txtBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 173, 244, -1));

        lblLicenseNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLicenseNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblLicenseNumber.setText("License Number:");
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 71, 91, 20));

        lblDateIssued.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateIssued.setForeground(new java.awt.Color(102, 102, 102));
        lblDateIssued.setText("Date Issued:");
        add(lblDateIssued, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 104, 91, 20));

        lblDateOfExpiration.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateOfExpiration.setForeground(new java.awt.Color(102, 102, 102));
        lblDateOfExpiration.setText("Date Of Expiration");
        add(lblDateOfExpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 135, -1, 20));

        lblBloodType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(102, 102, 102));
        lblBloodType.setText("Blood Type");
        add(lblBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 173, 91, 20));
        add(txtLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 71, 244, -1));
        add(txtDateIssued, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 104, 244, -1));
        add(txtDOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 140, 244, -1));

        lblUploadPicture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUploadPicture.setForeground(new java.awt.Color(102, 102, 102));
        lblUploadPicture.setText("DL Pic");
        add(lblUploadPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblDisplayPic.setBackground(new java.awt.Color(204, 204, 204));
        lblDisplayPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblDisplayPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCreateDL;
    private javax.swing.JLabel lblDateIssued;
    private javax.swing.JLabel lblDateOfExpiration;
    private javax.swing.JLabel lblDisplayPic;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblUploadPicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDateIssued;
    private javax.swing.JTextField txtLN;
    // End of variables declaration//GEN-END:variables

    private void displayDLInfo() {
        txtLN.setText(dLInformation.getLicenseNum());
        txtDateIssued.setText(dLInformation.getDateOfIssue());
        txtBloodType.setText(dLInformation.getBloodType());
        txtDOE.setText(dLInformation.getDateOfExpiry());
        
        
        
        try {
            ImageIcon i = new ImageIcon(ImageIO.read(new File(dLInformation.getPicture())));
            BufferedImage img = ImageIO.read(new File(dLInformation.getPicture()));
            Image ig = img.getScaledInstance(240, 100,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(ig);
            lblDisplayPic.setIcon(icon);
//            JLabel label = new JLabel(icon);
        }
        catch (Exception ex) {
            System.out.println("ERROR");
        }
    }
}
