/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_components;

import Model.AddressInformation;
import Model.BankingInformation;
import Model.DLInformation;
import Model.DemoGraphicInformation;
import Model.MedRecord;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author sushm
 */
public class ViewCompleteReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompleteReportJPanel
     */
    DemoGraphicInformation Demograp;
    AddressInformation addressInformation;
    BankingInformation savingsAccount;
    BankingInformation checkingAccount;
    DLInformation dLInformation;
    MedRecord medRecord;
    
    
    public ViewCompleteReportJPanel(DemoGraphicInformation demoGraphicInformation, AddressInformation addressInformation, BankingInformation savingsAccount, BankingInformation checkingAccount, DLInformation dLInformation, MedRecord medRecord) {
        initComponents();
        this.Demograp = demoGraphicInformation;
        this.addressInformation = addressInformation;
        this.checkingAccount = checkingAccount;
        this.dLInformation = dLInformation;
        this.savingsAccount = savingsAccount;
        this.medRecord = medRecord;
        displaycompleteReport();
        
    }

//    ViewCompleteReportJPanel(DemoGraphicInformation demoGraphicInformation, AddressInformation addressInformation, BankingInformation savingsAccount, BankingInformation checkingAccount, DLInformation dLInformation, MedRecord medRecord) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblStreetAdd = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutingNumber = new javax.swing.JLabel();
        lblBankAccountNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        txtBankNameSA = new javax.swing.JTextField();
        txtBRNumSA = new javax.swing.JTextField();
        txtAccNumSA = new javax.swing.JTextField();
        txtAccTypSA = new javax.swing.JTextField();
        txtAccBalSA = new javax.swing.JTextField();
        lblSavingAccount = new javax.swing.JLabel();
        txtAccNumCA = new javax.swing.JTextField();
        txtAccTypCA = new javax.swing.JTextField();
        txtAccBalCA = new javax.swing.JTextField();
        lblBankName1 = new javax.swing.JLabel();
        lblBankRoutingNumber1 = new javax.swing.JLabel();
        lblCheckingAccount = new javax.swing.JLabel();
        lblBankAccountNumber1 = new javax.swing.JLabel();
        lblAccountBalance1 = new javax.swing.JLabel();
        lblAccountType1 = new javax.swing.JLabel();
        txtBankNameCA = new javax.swing.JTextField();
        txtBRNumCA = new javax.swing.JTextField();
        lblCreateDL = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        lblDateIssued = new javax.swing.JLabel();
        lblDateOfExpiration = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        txtDateIssued = new javax.swing.JTextField();
        txtDOE = new javax.swing.JTextField();
        lblMedRecNum = new javax.swing.JLabel();
        lblAllergy1 = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        lblMedicalRecord = new javax.swing.JLabel();
        lblDLPic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 650));
        setMinimumSize(new java.awt.Dimension(500, 650));
        setPreferredSize(new java.awt.Dimension(500, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name:");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 20));

        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name:");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 60, 20));

        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Phone Number:");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 80, 20));

        lblDob.setForeground(new java.awt.Color(255, 255, 255));
        lblDob.setText("D.O.B:");
        add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 30, -1));

        lblHeight.setForeground(new java.awt.Color(255, 255, 255));
        lblHeight.setText("Height:");
        add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight:");
        add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        lblSSN.setForeground(new java.awt.Color(255, 255, 255));
        lblSSN.setText("SSN:");
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 40, -1));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 110, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 110, -1));
        add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, -1));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 110, -1));
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 110, -1));

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Demographic Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, -1));

        lblStreetAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetAdd.setText("Street Address:");
        add(lblStreetAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 10));

        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 10));

        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setText("State:");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 10));

        lblZipCode.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCode.setText("ZipCode:");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 10));

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 690, 20));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 20));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 20));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 100, 20));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Address Information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 20));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Complete Report");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 860, -1));

        lblBankName.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 118, 20));

        lblBankRoutingNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblBankRoutingNumber.setText("Bank Routing Number");
        add(lblBankRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 118, 20));

        lblBankAccountNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblBankAccountNumber.setText("Bank Account Number");
        add(lblBankAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 118, 20));

        lblAccountBalance.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountBalance.setText("Account Balance:");
        add(lblAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 118, 20));

        lblAccountType.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountType.setText("Account Type");
        add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 118, 20));
        add(txtBankNameSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 244, -1));
        add(txtBRNumSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 244, -1));
        add(txtAccNumSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 244, -1));
        add(txtAccTypSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 244, -1));
        add(txtAccBalSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 244, -1));

        lblSavingAccount.setBackground(new java.awt.Color(204, 204, 204));
        lblSavingAccount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSavingAccount.setForeground(new java.awt.Color(204, 255, 255));
        lblSavingAccount.setText("Saving Account");
        add(lblSavingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 438, -1));
        add(txtAccNumCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 240, -1));
        add(txtAccTypCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 240, -1));
        add(txtAccBalCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 240, -1));

        lblBankName1.setForeground(new java.awt.Color(255, 255, 255));
        lblBankName1.setText("Bank Name:");
        add(lblBankName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 70, 20));

        lblBankRoutingNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblBankRoutingNumber1.setText("Bank Routing Number:");
        add(lblBankRoutingNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 120, 20));

        lblCheckingAccount.setBackground(new java.awt.Color(204, 204, 204));
        lblCheckingAccount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCheckingAccount.setForeground(new java.awt.Color(204, 255, 255));
        lblCheckingAccount.setText("Checking Account");
        add(lblCheckingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 410, -1));

        lblBankAccountNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblBankAccountNumber1.setText("Bank Account Number:");
        add(lblBankAccountNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 120, 20));

        lblAccountBalance1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountBalance1.setText("Account Balance:");
        add(lblAccountBalance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 90, 20));

        lblAccountType1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountType1.setText("Account Type:");
        add(lblAccountType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 80, 20));
        add(txtBankNameCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 240, -1));
        add(txtBRNumCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 240, -1));

        lblCreateDL.setBackground(new java.awt.Color(204, 204, 204));
        lblCreateDL.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCreateDL.setForeground(new java.awt.Color(204, 255, 255));
        lblCreateDL.setText("Driver's License");
        add(lblCreateDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 510, 20));
        add(txtBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 244, -1));

        lblLicenseNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblLicenseNumber.setText("License Number:");
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 91, 20));

        lblDateIssued.setForeground(new java.awt.Color(255, 255, 255));
        lblDateIssued.setText("Date Issued:");
        add(lblDateIssued, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 91, 20));

        lblDateOfExpiration.setForeground(new java.awt.Color(255, 255, 255));
        lblDateOfExpiration.setText("Date Of Expiration");
        add(lblDateOfExpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, 20));

        lblBloodType.setForeground(new java.awt.Color(255, 255, 255));
        lblBloodType.setText("Blood Type");
        add(lblBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 91, 20));
        add(txtLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 244, -1));
        add(txtDateIssued, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 244, -1));
        add(txtDOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 244, -1));

        lblMedRecNum.setForeground(new java.awt.Color(255, 255, 255));
        lblMedRecNum.setText("Med Record Number:");
        add(lblMedRecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        lblAllergy1.setForeground(new java.awt.Color(255, 255, 255));
        lblAllergy1.setText("Allergy1:");
        add(lblAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, -1, -1));

        lblAllergy2.setForeground(new java.awt.Color(255, 255, 255));
        lblAllergy2.setText("Allergy2:");
        add(lblAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 730, -1, -1));

        lblAllergy3.setForeground(new java.awt.Color(255, 255, 255));
        lblAllergy3.setText("Allergy3:");
        add(lblAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 730, -1, -1));
        add(txtAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, 110, -1));

        txtAllergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy3ActionPerformed(evt);
            }
        });
        add(txtAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 730, 110, -1));
        add(txtMedRecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 480, -1));
        add(txtAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, 110, -1));

        lblMedicalRecord.setBackground(new java.awt.Color(204, 204, 204));
        lblMedicalRecord.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblMedicalRecord.setForeground(new java.awt.Color(204, 255, 255));
        lblMedicalRecord.setText("Medical Record");
        add(lblMedicalRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 230, 20));
        add(lblDLPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 70, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtAllergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy3ActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void displaycompleteReport() {
//        Demographic info
        txtFirstName.setText(Demograp.getFirstName());
        txtLastName.setText(Demograp.getLastName());
        txtPhoneNumber.setText(Demograp.getPhoneNumber());
        txtDob.setText(Demograp.getDateOfBirth());
        txtHeight.setText(Demograp.getHeight());
        txtWeight.setText(Demograp.getWeight());
        txtSSN.setText(Demograp.getSSN());
        txtAge.setText(Demograp.getAge());
        
//        Address Information
       
        txtCity.setText(addressInformation.getCity());
        txtStreet.setText(addressInformation.getStreetAddress());
        txtState.setText(addressInformation.getState());
        txtZipCode.setText(addressInformation.getZipCode());
        
//        Savings Account

        txtBankNameSA.setText(savingsAccount.getBankName());
        txtBRNumSA.setText(savingsAccount.getBankRountingNum());
        txtAccNumSA.setText(savingsAccount.getAccNum());
        txtAccBalSA.setText(savingsAccount.getAccBalance());
        txtAccTypSA.setText(savingsAccount.getAccType());
        
//        Checking Account

        txtBankNameCA.setText(checkingAccount.getBankName());
        txtBRNumCA.setText(checkingAccount.getBankRountingNum());
        txtAccNumCA.setText(checkingAccount.getAccNum());
        txtAccBalCA.setText(checkingAccount.getAccBalance());
        txtAccTypCA.setText(checkingAccount.getAccType());
        
//        DL Information

        txtLN.setText(dLInformation.getLicenseNum());
        txtDateIssued.setText(dLInformation.getDateOfIssue());
        txtBloodType.setText(dLInformation.getBloodType());
        txtDOE.setText(dLInformation.getDateOfExpiry());
        
        try {
            ImageIcon i = new ImageIcon(ImageIO.read(new File(dLInformation.getPicture())));
            BufferedImage img = ImageIO.read(new File(dLInformation.getPicture()));
            Image ig = img.getScaledInstance(70, 50,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(ig);
            lblDLPic.setIcon(icon);
//            JLabel label = new JLabel(icon);
        }
        catch (Exception ex) {
            System.out.println("ERROR");
        }
        
//        Medical Information
        
        txtMedRecNum.setText(medRecord.getMedRecordNum());
        txtAllergy1.setText(medRecord.getAlergy1());
        txtAllergy2.setText(medRecord.getAlergy2());
        txtAllergy3.setText(medRecord.getAlergy3());
        
    }   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountBalance1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblAccountType1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBankAccountNumber1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblBankRoutingNumber1;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCheckingAccount;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreateDL;
    private javax.swing.JLabel lblDLPic;
    private javax.swing.JLabel lblDateIssued;
    private javax.swing.JLabel lblDateOfExpiration;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblMedicalRecord;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSavingAccount;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAdd;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtAccBalCA;
    private javax.swing.JTextField txtAccBalSA;
    private javax.swing.JTextField txtAccNumCA;
    private javax.swing.JTextField txtAccNumSA;
    private javax.swing.JTextField txtAccTypCA;
    private javax.swing.JTextField txtAccTypSA;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtBRNumCA;
    private javax.swing.JTextField txtBRNumSA;
    private javax.swing.JTextField txtBankNameCA;
    private javax.swing.JTextField txtBankNameSA;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOE;
    private javax.swing.JTextField txtDateIssued;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
